../src/bin_counter_load.sv
../src/pc_reg.sv
../src/sdp_sc_ram.sv
../src/FIFO.sv
../src/mux_4to1.sv
../src/mux_2to1.sv
../src/IFQ_ctrl.sv
../src/IFQ.sv
../src/i_cache.sv
../tb_src/IFQ_if.sv
../tb_src/tb_package.sv
tb_top.sv